# Name of site (displayed in the header)
name: That was a joke

# Short bio or description (displayed in the header)
description: HAHA fat chance

# URL of avatar or profile pic
avatar: /images/avatar.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: serrintine
  instagram: 
  linkedin: 
  pinterest: 
  rss: # just type anything here for a working RSS icon
  twitter: serrintine
  stackoverflow:

# Disqus shortname, entering this will enable commenting on posts
disqus: 

# Enter Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: 

# Website URL
# Used for Sitemap.xml and RSS feed
url: http://serrintine.github.io

# Add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! Don't need to change any of the configuration flags below !!
#

markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
permalink: /:title/

# Set the Sass partials directory
sass:
  sass_dir: _sass
  style: :compressed # Either :expanded or :compressed

# Use the following plug-ins
gems:
  - jemoji # Emoji please!
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
		- config.rb
		- Rakefile
		- bower.json
		- bower_components
